= Setup
include::_attributes.adoc[]

[依赖工具]
- kubernetes
- docker
- istio
- siege
- git
- maven
- [stern](https://github.com/wercker/stern)

[source,bash]
----

oc apply -f install/kubernetes/helm/istio/templates/crds.yaml
or
kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml


oc apply -f install/kubernetes/istio-demo.yaml
or
kubectl apply -f install/kubernetes/istio-demo.yaml

oc project istio-system
or
kubectl config set-context $(kubectl config current-context) --namespace=istio-system

oc expose svc istio-ingressgateway
oc expose svc servicegraph
oc expose svc grafana
oc expose svc prometheus
oc expose svc tracing
----

Wait for Istio's components to be ready

[source,bash]
----
$ oc get pods -w
or
$ kubectl get pods -w

NAME                                        READY     STATUS      RESTARTS   AGE
grafana-6995b4fbd7-ntp4f                    1/1       Running     0          57m
istio-citadel-54f4678f86-jnv5s              1/1       Running     0          57m
istio-cleanup-secrets-nch4k                 0/1       Completed   0          57m
istio-egressgateway-5d7f8fcc7b-r76gg        1/1       Running     0          57m
istio-galley-7bd8b5f88f-nlczb               1/1       Running     0          57m
istio-grafana-post-install-lffq2            0/1       Completed   0          57m
istio-ingressgateway-6f58fdc8d7-gbzzq       1/1       Running     0          57m
istio-pilot-d99689994-zh66q                 2/2       Running     0          57m
istio-policy-766bf4bd6d-skwkp               2/2       Running     0          57m
istio-sidecar-injector-85ccf84984-crmhv     1/1       Running     0          57m
istio-statsd-prom-bridge-55965ff9c8-76nx4   1/1       Running     0          57m
istio-telemetry-55b6b5bbc7-qmf2l            2/2       Running     0          57m
istio-tracing-77f9f94b98-kknh7              1/1       Running     0          57m
prometheus-7456f56c96-nxdvv                 1/1       Running     0          57m
servicegraph-684c85ffb9-f7tjp               1/1       Running     2          57m
----

And if you need quick access to the OpenShift console

[source,bash]
----
minishift console
----

NOTE: On your first launch of the OpenShift console via `minishift`, you will receive a warning like "Your connection is not private". For our demo, simply select "Proceed to 192.168.xx.xx (unsafe)" to bypass the warning. Both the username and the password are set to `admin`, thanks to the `admin-user` add-on.


[#redhatistioinstallation]
== (Option 2) Red Hat OpenShift Service Mesh installation

The Red Hat OpenShift Service Mesh uses an operator to install all Istio components and to set all permissions. You also get Jaeger and Kaili pre-installed in the bundle.

Before start, you have to enable mutating and validating admission webhook plugins

[source,bash]
----
#!/bin/bash

minishift openshift config set --target=kube --patch '{
    "admissionConfig": {
        "pluginConfig": {
            "ValidatingAdmissionWebhook": {
                "configuration": {
                    "apiVersion": "apiserver.config.k8s.io/v1alpha1",
                    "kind": "WebhookAdmission",
                    "kubeConfigFile": "/dev/null"
                }
            },
            "MutatingAdmissionWebhook": {
                "configuration": {
                    "apiVersion": "apiserver.config.k8s.io/v1alpha1",
                    "kind": "WebhookAdmission",
                    "kubeConfigFile": "/dev/null"
                }
            }
        }
    }
}'
----

You also need to set the system limits on `mmap` counts otherwise Elasticsearch will fail.
Jaeger uses Elasticsearch and it is part of the Red Hat OpenShift Service Mesh.
Elasticsearch uses a `mmapfs` directory by default to store its indices.
The default operating system limits on `mmap` counts is likely to be too low, which may result in out of memory exceptions.
To fix this you have to login into the minishift instance and do the following

[source,bash]
----
$ minishift ssh
[docker@istio-tutorial ~]$ sudo -i
[root@istio-tutorial ~]$ echo "vm.max_map_count = 262144" > /etc/sysctl.d/99-elasticsearch.conf
[root@istio-tutorial ~]$ sysctl vm.max_map_count=262144
[root@istio-tutorial ~]$ exit
logout
[docker@istio-tutorial ~]$ exit
logout
----

Download the Istio release and add `istioctl` to your path so later in this tutorial you can use it to manually inject the sidecars.

NOTE: Another option would be to add the annotation `sidecar.istio.io/inject: "true"` in the deployment files so the sidecar is injected automatically.

[source,bash]
----
#!/bin/bash

# Mac OS:
curl -L https://github.com/istio/istio/releases/download/1.0.5/istio-1.0.5-osx.tar.gz | tar xz

# Fedora/RHEL:
curl -L https://github.com/istio/istio/releases/download/1.0.5/istio-1.0.5-linux.tar.gz | tar xz

# Both:
pushd istio-1.0.5
export ISTIO_HOME=`pwd`
export PATH=$ISTIO_HOME/bin:$PATH
popd

----

Now your system is prepared and we can install Istio operator

[source,bash]
----
#!/bin/bash

oc new-project istio-operator
oc new-app -f https://raw.githubusercontent.com/Maistra/openshift-ansible/maistra-0.6/istio/istio_community_operator_template.yaml --param=OPENSHIFT_ISTIO_MASTER_PUBLIC_URL="https://$(minishift ip):8443"
----

Wait for the operator to be ready

[source,bash]
----
$ oc get pods -w -n istio-operator

NAME                              READY     STATUS    RESTARTS   AGE
istio-operator-58c45d8f64-jdsrz   1/1       Running   0          10s
----

Once operator is ready, create an installation for Istio

[source,bash]
----
#!/bin/bash
oc project istio-operator
cat <<EOF >/tmp/istio-cr.yaml
apiVersion: "istio.openshift.com/v1alpha1"
kind: "Installation"
metadata:
  name: "istio-installation"
  namespace: istio-operator
spec:
  deployment_type: openshift
  istio:
    authentication: false
    community: false
    prefix: openshift-istio-tech-preview/
    version: 0.6.0
  jaeger:
    prefix: distributed-tracing-tech-preview/
    version: 1.9.0
    elasticsearch_memory: 1Gi
  kiali:
    prefix: openshift-istio-tech-preview/
    version: 0.13.0
    username: admin
    password: admin
EOF
oc create -f /tmp/istio-cr.yaml
----

Wait for Istio's components to be ready

[source,bash]
----
$ oc get pods -n istio-system

NAME                                          READY     STATUS      RESTARTS   AGE
elasticsearch-0                               1/1       Running     0          3m
grafana-648c7d5cc6-d4cgr                      1/1       Running     0          3m
istio-citadel-64f86c964-vjd6f                 1/1       Running     0          5m
istio-egressgateway-8579f6f649-zwmqh          1/1       Running     0          5m
istio-galley-569c79fcbf-rc24l                 1/1       Running     0          5m
istio-ingressgateway-5457546784-gct2p         1/1       Running     0          5m
istio-pilot-78d8f7465f-kmclw                  2/2       Running     0          5m
istio-policy-b57648f9f-cvj82                  2/2       Running     0          5m
istio-sidecar-injector-5876f696f-s2pdt        1/1       Running     0          5m
istio-statsd-prom-bridge-549d687fd9-g2gmc     1/1       Running     0          5m
istio-telemetry-56587b8fb6-wpg9k              2/2       Running     0          5m
jaeger-agent-6qgrl                            1/1       Running     0          3m
jaeger-collector-9cbd5f46c-kt9w9              1/1       Running     0          3m
jaeger-query-6678967b5-8sgdp                  1/1       Running     0          3m
kiali-6b8c686d9b-mkxdv                        1/1       Running     0          2m
openshift-ansible-istio-installer-job-rj7pj   0/1       Completed   0          7m
prometheus-6ffc56584f-zgbv8                   1/1       Running     0          5m
----


