= Deploy Microservices
include::_attributes.adoc[]

[#deploycustomer]
## Deploy customer

创建 tutorial namespace 

[source,bash]
----
kubectl create namespace tutorial
kubectl config set-context $(kubectl config current-context) --namespace=tutorial
----

允许内部服务使用 `ISTIO_MUTUAL` 方式进行认证

```
cat <<EOF | kubectl apply -f -
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "tutorial"
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF
```

使用 istio-gateway 访问服务

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
  namespace: "tutorial"
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer
  namespace: "tutorial"
spec:
  hosts:
  - "*"
  gateways:
  - my-gateway
  http:
  - route:
    - destination:
        host: customer
        port:
          number: 8080
EOF
```

克隆源代码

[source,bash]
----
git clone https://github.com/redhat-developer-demos/istio-tutorial
cd istio-tutorial
----

### 构建 docker 镜像

NOTE: Your very first Docker build will take a bit of time as it downloads all the layers. Subsequent rebuilds of the Docker image, updating only the microservice layer will be very fast.

[source,bash]
----
cd customer/java/springboot
mvn clean package
docker build -t docker build -t kuopsme/reahat.istio.customer .
docker images | grep reahat.istio.customer
docker push kuopsme/reahat.istio.customer
----

现在部署 customer pod 和 sidecar 容器

[source,bash,subs="+macros,+attributes"]
----
sed -i 's@example/customer:latest@kuopsme/reahat.istio.customer:latest@g' ../../kubernetes/Deployment.yml
kubectl apply -f <(istioctl kube-inject -f ../../kubernetes/Deployment.yml) -n tutorial
kubectl create -f ../../kubernetes/Service.yml -n tutorial
----

=== Expose customer

 `customer` service 使用 ingress-gateway 方式进行暴漏

[source,bash]
----
export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}')
export INGRESS_HOST=$(kubectl get po -l istio=ingressgateway -n istio-system -o 'jsonpath={.items[0].status.hostIP}')
----

IMPORTANT: If your pod fails with `ImagePullBackOff`, it's possible that your current terminal isn't using the proper Docker Environment. See link:#setup-environment[Setup environment].

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

访问 url 测试,默认地址为 31380

[source,bash]
----
curl $INGRESS_HOST:$INGRESS_PORT
----

你可以看到如下错误输出，因为 services `preference` 和 `recommendation` 并没有部署.

----
customer => I/O error on GET request for "http://preference:8080": preference; nested exception is java.net.UnknownHostException: preference
----

也可以使用以下方式查看 log

[source,bash]
----
stern $(kubectl get pods|grep customer|awk '{ print $1 }'|head -1) -c customer
----

你应该跟踪到以下关键信息:

[source,bash]
----
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://preference:8080": preference; nested exception is java.net.UnknownHostException: preference
----

返回 istio-tutorial 主目录

[source,bash]
----
cd ../../..
----

[#deploypreference]
== Deploy preference

=== 构建 preference 服务的 docker 镜像

[source,bash,subs="+macros,+attributes"]
----
cd preference/java/springboot
mvn clean package
docker build -t kuopsme/reahat.istio.preference:v1 .
docker images | grep reahat.istio.preference
docker push kuopsme/reahat.istio.preference:v1

sed -i 's@example/preference:v1@kuopsme/reahat.istio.preference:v1@g'  ../../kubernetes/Deployment.yml
kubectl apply -f <(istioctl kube-inject -f ../../kubernetes/Deployment.yml) -n tutorial
kubectl create -f ../../kubernetes/Service.yml -n tutorial
----

=== 等待 preference 部署完毕

[source, bash]
----
kubectl get pods -w
----

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

此时，再访问 customer

[source,bash]
----
curl $INGRESS_HOST:$INGRESS_PORT
----

返回结果如下，返回 一个错误，因为 `recommendation` 服务没有部署

NOTE: We could make this a bit more resilient in a future iteration of this tutorial

[source,bash]
----
customer => 503 preference => I/O error on GET request for "http://recommendation:8080": recommendation; nested exception is java.net.UnknownHostException: recommendation
----

也可以查看日志

[source,bash]
----
stern $(kubectl get pods|grep preference|awk '{ print $1 }'|head -1) -c preference
----

应该看到有如下错误输出:

[source,bash]
----
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://recommendation:8080": recommendation; nested exception is java.net.UnknownHostException: recommendation
----

返回 istio-tutorial 主目录

[source,bash]
----
cd ../../..
----

[#deployrecommendation]
== 部署 recommendation

IMPORTANT: The tag `v1` at the end of the image name matters. We will be creating a `v2` version of `recommendation` later in this tutorial. Having both a `v1` and `v2` version of the `recommendation` code will allow us to exercise some interesting aspects of Istio's capabilities.

=== Recommendation build docker 镜像，并部署

[source,bash,subs="+macros,+attributes"]
----
cd recommendation/java/vertx
mvn clean package
docker build -t kuopsme/reahat.istio.recommendation:v1 .
docker images | grep kuopsme/reahat.istio.recommendation
docker push kuopsme/reahat.istio.recommendation:v1

sed -i 's@example/recommendation:v1@kuopsme/reahat.istio.recommendation:v1@g'  ../../kubernetes/Deployment.yml 
kubectl apply -f <(istioctl kube-inject -f ../../kubernetes/Deployment.yml) -n tutorial
kubectl create -f ../../kubernetes/Service.yml -n tutorial
kubectl get pods -w
----

=== Wait recommendation to be deployed

等到状态变为 `Running` 并且 pods  `就绪` 列为 `2/2` . To exit, press `Ctrl+C`

[source,bash]
----
curl $INGRESS_HOST:$INGRESS_PORT
----

正常应该返回如下结果:

[source,bash]
----
customer => preference => recommendation v1 from '76d747d99f-25h79': 1
----

同样可以查看  `recommendation` 的日志

[source,bash]
----
stern $(kubectl get pods|grep recommendation-v1|awk '{ print $1 }'|head -1) -c recommendation
----

返回 `istio-tutorial` 主目录

[source,bash]
----
cd ../../..
----

[#redeployingcode]
== Updating Redeploying Code

When you wish to change code (e.g. editing the .java files) and wish to "redeploy", simply:

[source,bash]
----
cd {servicename}/java/{springboot|vertx}

vi src/main/java/com/redhat/developer/demos/{servicename}/{Servicename}{Controller|Verticle}.java
----

Make your changes, save it and then:

[source,bash]
----
mvn clean package
docker build -t example/{servicename}:v1 .

oc get pods -o jsonpath='{.items[*].metadata.name}' -l app={servicename}
oc get pods -o jsonpath='{.items[*].metadata.name}' -l app={servicename},version=v1
oc delete pod -l app={servicename},version=v1

or

kubectl get pods -o jsonpath='{.items[*].metadata.name}' -l app={servicename}
kubectl get pods -o jsonpath='{.items[*].metadata.name}' -l app={servicename},version=v1
kubectl delete pod -l app={servicename},version=v1
----

Why the delete pod?

Based on the Deployment configuration, Kubernetes/OpenShift will recreate the pod, based on the new docker image as it attempts to keep the desired replicas available

[source,bash]
----
oc describe deployment {servicename} | grep Replicas
or
kubectl describe deployment {servicename} | grep Replicas
----
