= Advanced Route Rules
include::_attributes.adoc[]

[IMPORTANT]
.开始之前
====
清理之前的 tuorial namespace 中的 istio 资源

[source, bash,subs="+macros,+attributes"]
----
./scripts/clean.sh tutorial
----

添加 mtls 认证，和 gateway

```
cat <<EOF | kubectl apply -f -
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "tutorial"
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF

cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
  namespace: "tutorial"
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer
  namespace: "tutorial"
spec:
  hosts:
  - "*"
  gateways:
  - my-gateway
  http:
  - route:
    - destination:
        host: customer
        port:
          number: 8080
EOF
```

[#canarydeploymentuseragent]
== Smart routing based on user-agent header (Canary Deployment)

通过 header 进行路由的演示服务

[#alltorecommendationv1]
=== Set recommendation to all v1

将所有 recommendation 服务的请求路由到 v1

[source,bash,subs="+macros,+attributes"]
----
istioctl create -f istiofiles/destination-rule-recommendation-v1-v2.yml -n tutorial
istioctl create -f istiofiles/virtual-service-recommendation-v1.yml -n tutorial
----

[#safaritov2]
=== Set Safari users to v2

将 safari 用户的流量路由到 v2

[source,bash,subs="+macros,+attributes"]
----
istioctl replace -f istiofiles/virtual-service-safari-recommendation-v2.yml -n tutorial

istioctl get virtualservice -n tutorial

curl -A Safari $INGRESS_HOST:$INGRESS_PORT
#使用 Firfox 测试
curl -A Firefox $INGRESS_HOST:$INGRESS_PORT
----

可以查看详细的配置

[source,bash,subs="+macros,+attributes"]
----
istioctl get virtualservice -o yaml -n tutorial
----

==== Remove the Safari rule

移除 safari 规则

[source,bash,subs="+macros,+attributes"]
----
istioctl delete -f istiofiles/virtual-service-safari-recommendation-v2.yml -n tutorial
----

[#mobiletov2]
=== Set mobile users to v2

将移动用户的流量路由到 v2 

[source,bash,subs="+macros,+attributes"]
----
istioctl create -f istiofiles/virtual-service-mobile-recommendation-v2.yml -n tutorial

curl -A "Mozilla/5.0 (iPhone; U; CPU iPhone OS 4(KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5" $INGRESS_HOST:$INGRESS_PORT
----

==== Clean up

[source,bash,subs="+macros,+attributes"]
----
istioctl delete -f istiofiles/destination-rule-recommendation-v1-v2.yml -n tutorial
istioctl delete -f istiofiles/virtual-service-mobile-recommendation-v2.yml -n tutorial
----


[#mirroringtraffic]
== Mirroring Traffic (Dark Launch)

流量镜像

[source,bash,subs="+macros,+attributes"]
----
istioctl create -f istiofiles/destination-rule-recommendation-v1-v2.yml -n tutorial
istioctl create -f istiofiles/virtual-service-recommendation-v1-mirror-v2.yml -n tutorial

curl $INGRESS_HOST:$INGRESS_PORT
----

查看 recommendation-v2 的log

[source,bash]
----
kubectl logs -f `kubectl get pods|grep recommendation-v2|awk '{ print $1 }'` -c recommendation
----

=== Clean up

[source,bash,subs="+macros,+attributes"]
----
istioctl delete -f istiofiles/destination-rule-recommendation-v1-v2.yml -n tutorial
istioctl delete -f istiofiles/virtual-service-recommendation-v1-mirror-v2.yml -n tutorial
----


[#loadbalancer]
== Load Balancer

By default, you will see "round-robin" style load-balancing, but you can change it up, with the RANDOM option being fairly visible to the naked eye.

Add another v2 pod to the mix

[source,bash,subs="+macros,+attributes"]
----
oc scale deployment recommendation-v2 --replicas=2 -n tutorial{namespace-suffix}
or
kubectl scale deployment recommendation-v2 --replicas=2 -n tutorial{namespace-suffix}
----

Wait a bit (oc get pods -w to watch)
and curl the customer endpoint many times

[source,bash,subs="+macros,+attributes"]
----
curl customer-tutorial{namespace-suffix}.{appdomain}
----

Add a 3rd v2 pod to the mix

[source,bash,subs="+macros,+attributes"]
----
$ oc scale deployment recommendation-v2 --replicas=3 -n tutorial{namespace-suffix}
$ oc get pods -n tutorial{namespace-suffix}

or 

$ kubectl scale deployment recommendation-v2 --replicas=3 -n tutorial{namespace-suffix}
$ kubectl get pods -n tutorial{namespace-suffix}


NAME                                  READY     STATUS    RESTARTS   AGE
customer-1755156816-cjd2z             2/2       Running   0          1h
preference-3336288630-2cc6f          2/2       Running   0          1h
recommendation-v1-3719512284-bn42p   2/2       Running   0          59m
recommendation-v2-2815683430-97nnf   2/2       Running   0          43m
recommendation-v2-2815683430-d49n6   2/2       Running   0          51m
recommendation-v2-2815683430-tptf2   2/2       Running   0          33m
----

Wait for those 2/2 (two containers in each pod) and then poll the customer endpoint:

[source, bash,subs="+macros,+attributes"]
----
./scripts/run.sh http://customer-tutorial{namespace-suffix}.{appdomain}
----

The results should follow a fairly normal round-robin distribution pattern

[source,bash]
----
customer => preference => recommendation v1 from '99634814-d2z2t': 1145
customer => preference => recommendation v2 from '2819441432-525lh': 1
customer => preference => recommendation v2 from '2819441432-rg45q': 2
customer => preference => recommendation v2 from '2819441432-bs5ck': 181
customer => preference => recommendation v1 from '99634814-d2z2t': 1146
customer => preference => recommendation v2 from '2819441432-rg45q': 3
customer => preference => recommendation v2 from '2819441432-rg45q': 4
customer => preference => recommendation v2 from '2819441432-bs5ck': 182
----

Now, add the Random LB DestinationPolicy

[source,bash,subs="+macros,+attributes"]
----
istioctl create -f link:{github-repo}/{istiofiles-dir}/destination-rule-recommendation_lb_policy_app.yml[istiofiles/destination-rule-recommendation_lb_policy_app.yml] -n tutorial{namespace-suffix}
----

And you should see a different pattern of which pod is being selected

[source,bash]
----
customer => preference => recommendation v2 from '2819441432-rg45q': 10
customer => preference => recommendation v2 from '2819441432-525lh': 3
customer => preference => recommendation v2 from '2819441432-rg45q': 11
customer => preference => recommendation v1 from '99634814-d2z2t': 1153
customer => preference => recommendation v1 from '99634814-d2z2t': 1154
customer => preference => recommendation v1 from '99634814-d2z2t': 1155
customer => preference => recommendation v2 from '2819441432-rg45q': 12
customer => preference => recommendation v2 from '2819441432-525lh': 4
customer => preference => recommendation v2 from '2819441432-525lh': 5
customer => preference => recommendation v2 from '2819441432-rg45q': 13
customer => preference => recommendation v2 from '2819441432-rg45q': 14
----

=== Clean up

[source,bash,subs="+macros,+attributes"]
----
istioctl delete -f istiofiles/destination-rule-recommendation_lb_policy_app.yml -n tutorial{namespace-suffix}

oc scale deployment recommendation-v2 --replicas=1 -n tutorial{namespace-suffix}
or
kubectl scale deployment recommendation-v2 --replicas=1 -n tutorial{namespace-suffix}
----
