= Simple Route Rules
include::_attributes.adoc[]

For this use case, we need to create a modified version of Recommendations

ifndef::workshop[]

[#deployrecommendationv2]
== Create recommendation:v2

更改 `RecommendationVerticle.java` 的以下行, 将 v1 改为 v2 并创建 "v2" docker image.

[source,java]
----
vim recommendation/java/vertx/src/main/java/com/redhat/developer/demos/recommendation/RecommendationVerticle.java 

# 第 18 行
private static final String RESPONSE_STRING_FORMAT = "recommendation v2 from '%s': %d\n";
----

The "v2" tag during the Docker build is significant.

There is also a second `deployment.yml` file to label things correctly

=== Docker build (if you have access to Docker daemon)

[source,bash]
----
cd recommendation/java/vertx
mvn clean package
docker build -t kuopsme/reahat.istio.recommendation:v2 .
docker push kuopsme/reahat.istio.recommendation:v2

# docker images | grep recommendation
kuopsme/reahat.istio.recommendation   v2                  3531fadb7787        5 minutes ago       449MB
kuopsme/reahat.istio.recommendation   v1                  12ae5ff9e87b        3 hours ago         449MB
----

IMPORTANT: We have a 2nd Deployment to manage the v2 version of recommendation. 

创建 v2 的 deployment.yaml

[source,bash,subs="+macros,+attributes"]
----
sed -i 's@example/recommendation:v2@kuopsme/reahat.istio.recommendation:v2@g'  ../../kubernetes/Deployment-v2.yml
kubectl apply -f <(istioctl kube-inject -f ../../kubernetes/Deployment-v2.yml) -n tutorial
kubectl get pods -w -n tutorial
----

=== Wait for v2 to be deployed

Wait for those pods to show "2/2", the istio-proxy/envoy sidecar is part of that pod

[source,bash,subs="+macros,+attributes"]
----
# kubectl get pod
NAME                                 READY   STATUS    RESTARTS   AGE
customer-57774fb87f-zm4xz            2/2     Running   0          3h26m
preference-v1-9588dbcd5-npt66        2/2     Running   0          3h21m
recommendation-v1-76d747d99f-25h79   2/2     Running   0          160m
recommendation-v2-bbb595df6-gm8v4    2/2     Running   0          2m26s
----

and test the customer endpoint

[source,bash,subs="+macros,+attributes"]
----
curl http://$INGRESS_HOST:$INGRESS_PORT
----

你可以在响应中看到 `v1 from '76d747d99f-25h79'` 字符串, `recommendation-v1-76d747d99f-25h79` 是 pod 的第三个字段 replicaset 的随机字符串

[source,bash, subs="+macros,+attributes"]
----
#curl $INGRESS_HOST:$INGRESS_PORT
customer => preference => recommendation v1 from '76d747d99f-25h79': 181
----

你也可以在响应中看到 `v2 from 'bbb595df6-gm8v4'` 字符串, `recommendation-v2-bbb595df6-gm8v4` 是 pod 的第三个字段 replicaset 的随机字符串

```
# curl $INGRESS_HOST:$INGRESS_PORT
customer => preference => recommendation v2 from 'bbb595df6-gm8v4': 4
```



[source, bash, subs="+macros,+attributes"]
----
./scripts/run.sh http://customer-tutorial{namespace-suffix}.{appdomain}
----

kubernetes 默认的负载均衡策略是 round-robin 所有的可用 pods 在一个 service 中. 我们添加一个 v2 的 pod 测试

[source,bash,subs="+macros,+attributes"]
----
kubectl scale --replicas=2 deployment/recommendation-v2 -n tutorial
----

我们可以在结果中查看出负载均衡策略

[source,bash]
----
# kubectl get pod
NAME                                 READY   STATUS    RESTARTS   AGE
customer-57774fb87f-zm4xz            2/2     Running   0          3h39m
preference-v1-9588dbcd5-npt66        2/2     Running   0          3h35m
recommendation-v1-76d747d99f-25h79   2/2     Running   0          173m
recommendation-v2-bbb595df6-92tjz    2/2     Running   0          25s
recommendation-v2-bbb595df6-gm8v4    2/2     Running   0          15m

# curl $INGRESS_HOST:$INGRESS_PORT
customer => preference => recommendation v1 from '76d747d99f-25h79': 184

# curl $INGRESS_HOST:$INGRESS_PORT
customer => preference => recommendation v2 from 'bbb595df6-92tjz': 1

# curl $INGRESS_HOST:$INGRESS_PORT
customer => preference => recommendation v2 from 'bbb595df6-gm8v4': 7

# curl $INGRESS_HOST:$INGRESS_PORT
customer => preference => recommendation v1 from '76d747d99f-25h79': 185

# curl $INGRESS_HOST:$INGRESS_PORT
customer => preference => recommendation v2 from 'bbb595df6-92tjz': 2
----

将 v2 版本的 pod 缩减到原来的 1个

[source,bash,subs="+macros,+attributes"]
----
kubectl scale --replicas=1 deployment/recommendation-v2 -n tutorial
----

回到主目录

[source,bash]
----
cd ../../..
----
endif::workshop[]

[#istiorouting]
== Changing Istio Routings

[#alltorecommendationv2]
=== All users to recommendation:v2

将所有的 istio 到达 recommendation 服务的流量都导入到 v2 版本

[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f istiofiles/destination-rule-recommendation-v1-v2.yml -n tutorial
kubectl apply -f istiofiles/virtual-service-recommendation-v2.yml -n tutorial

curl $INGRESS_HOST:$INGRESS_PORT
----

你应该只看到返回结果中只有 `v2`

[#alltorecommendationv1]
=== All users to recommendation:v1

将所有的流量都导入 recommendation 服务的 v1 版本

Note: "replace" instead of "create" since we are overlaying the previous rule

[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f istiofiles/virtual-service-recommendation-v1.yml -n tutorial

# istioctl get virtualservice
VIRTUAL-SERVICE NAME   GATEWAYS     HOSTS            #HTTP     #TCP      NAMESPACE   AGE
customer               my-gateway   *                    1        0      tutorial    4h
recommendation                      recommendation       1        0      tutorial    6m

istioctl get virtualservice -o yaml -n tutorial
----

[#alltorecommendationv1v2]
=== All users to recommendation v1 and v2

删除规则，将流量导入 v1 和 v2 版

[source,bash,subs="+macros,+attributes"]
----
istioctl delete -f istiofiles/virtual-service-recommendation-v1.yml -n tutorial
----

使用 curl 命令测试

[source,bash,subs="+macros,+attributes"]
----
curl $INGRESS_HOST:$INGRESS_PORT
----

[#canarydeploymentrecommendation]
=== Canary deployment: Split traffic between v1 and v2

Canary Deployment scenario: push v2 into the cluster but slowly send end-user traffic to it, if you continue to see success, continue shifting more traffic over time

[source,bash,subs="+macros,+attributes"]
----
$ oc get pods -l app=recommendation -n tutorial{namespace-suffix}
or
$ kubectl get pods -l app=recommendation -n tutorial{namespace-suffix}

NAME                                  READY     STATUS    RESTARTS   AGE
recommendation-v1-3719512284-7mlzw   2/2       Running   6          2h
recommendation-v2-2815683430-vn77w   2/2       Running   0          1h
----

Create the `virtualservice` that will send 90% of requests to v1 and 10% to v2

[source,bash,subs="+macros,+attributes"]
----
istioctl create -f link:{github-repo}/{istiofiles-dir}/virtual-service-recommendation-v1_and_v2.yml[istiofiles/virtual-service-recommendation-v1_and_v2.yml] -n tutorial{namespace-suffix}
----

and send in several requests:

[source, bash,subs="+macros,+attributes"]
----
./scripts/run.sh http://customer-tutorial{namespace-suffix}.{appdomain}
----

In another terminal, change the mixture to be 75/25

[source,bash,subs="+macros,+attributes"]
----
istioctl replace -f link:{github-repo}/{istiofiles-dir}/virtual-service-recommendation-v1_and_v2_75_25.yml[istiofiles/virtual-service-recommendation-v1_and_v2_75_25.yml] -n tutorial{namespace-suffix}
----

Clean up

[source,bash,subs="+macros,+attributes"]
----
istioctl delete -f istiofiles/virtual-service-recommendation-v1_and_v2_75_25.yml -n tutorial{namespace-suffix}
istioctl delete -f istiofiles/destination-rule-recommendation-v1-v2.yml -n tutorial{namespace-suffix}
----


or you can run:

[source, bash,subs="+macros,+attributes"]
----
./scripts/clean.sh tutorial{namespace-suffix}
----
